name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: dist

      - name: Copy files from main
        run: |
          git fetch --depth=1 origin main
          git restore --source=origin/main --no-overlay serpinfo

      - name: Update timestamp
        run: |
          git add -N serpinfo
          timestamp=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
          for file in serpinfo/*.yml; do
            if git diff --quiet -I"^lastModified: " "$file"; then
              git restore "$file"
            else
              sed -i "s/^lastModified: .*/lastModified: $timestamp/" "$file"
            fi
          done

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          permission-contents: write

      - name: Commit changes
        uses: suzuki-shunsuke/commit-action@06e3b49d4706498d325d29bd85adc82ecf2f5d8f # v1.0.0
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          branch: dist
          commit_message: Update SERPINFO
