name: Format and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format by Biome
        run: pnpm biome format --write

      - name: Format by Prettier
        run: pnpm prettier --write '**/*.{md,yaml,yml}'

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "format by biome and prettier [skip ci]"
            git push
          fi
  deploy:
    needs: format

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: dist

      - name: Copy files from main
        run: |
          git fetch --depth=1 origin main
          git restore --source=origin/main --no-overlay serpinfo

      - name: Update timestamp
        run: |
          git add -N serpinfo
          timestamp=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
          for file in serpinfo/*.yml; do
            timestamp_line=$(grep -n -m1 "^lastModified: " "$file") || continue
            diff_stat=$(git diff --numstat "$file")
            if [[ $diff_stat =~ ^1[[:space:]]+1[[:space:]]+ ]]; then
              git restore "$file"
            else
              sed -i "${timestamp_line%%:*}s/.*/lastModified: $timestamp/" "$file"
            fi
          done

      - name: Commit changes
        run: |
          if ! git diff --quiet serpinfo; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add serpinfo
            git commit -m "update serpinfo"
            git push
          fi
