name: Update SearXNG Instances

on:
  schedule:
    - cron: "0 15 * * 5"
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  update-searxng-instances:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Update SearXNG instances
        run: pnpm update-searxng-instances

      - name: Generate token for pull request
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ vars.PULL_REQUESTS_APP_ID }}
          private-key: ${{ secrets.PULL_REQUESTS_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "searxng: update instances"
          branch: update-searxng-instances
          title: Update SearXNG instances
