name: Update SearXNG Instances

on:
  schedule:
    - cron: "0 15 * * 5"
  workflow_dispatch: {}

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  update-searxng-instances:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: true
          cache: true

      - name: Update SearXNG instances
        run: pnpm update-searxng-instances

      - name: Generate token for pull request
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.PULL_REQUESTS_APP_ID }}
          private-key: ${{ secrets.PULL_REQUESTS_PRIVATE_KEY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "searxng: update instances"
          branch: update-searxng-instances
          title: Update SearXNG instances
